//
//  CreateMapView.swift
//  EdukARt-Rebuild
//
//  Provides the user interface for creating a new map.
//  The AprilTag map is generated by the shared
//  AprilTagMapBuilder while the AR camera remains active.
//

import SwiftUI


// MARK: - Create Map View

struct CreateMapView: View {

    @ObservedObject var mapBuilder:
        AprilTagMapBuilder

    @ObservedObject var gameMapStore:
        GameMapStore
    
    @StateObject private var track = Track()
    
    @State private var isCreatingMap =
        false


    @State private var mapName =
        ""

    @State private var showNameDialog =
        false


    // MARK: - Body

    var body: some View {

        ZStack {

            // --------------------------------------------------
            // Semi-transparent background
            // --------------------------------------------------

            Color.black
                .opacity(0.8)
                .ignoresSafeArea()


            // --------------------------------------------------
            // Content
            // --------------------------------------------------

            VStack(
                spacing: 20
            ) {

                // MARK: Title

                Button(
                    "Create Map"
                ) {

                    mapBuilder.reset()

                    isCreatingMap =
                        true
                }
                
                .font(
                    .title2
                        .bold()
                )
                .foregroundStyle(
                    .white
                )


                // MARK: Instructions

                Text(
                    mapBuilder.referenceTagID == nil
                    ? "Scan the first AprilTag to define the map reference."
                    : "Move through the room and scan the remaining AprilTags."
                )
                .font(
                    .subheadline
                )
                .foregroundStyle(
                    .white.opacity(0.8)
                )


                // MARK: Reference Tag

                if let referenceTagID =
                    mapBuilder.referenceTagID {

                    HStack {

                        Circle()
                            .fill(
                                .white
                            )
                            .frame(
                                width: 8,
                                height: 8
                            )

                        Text(
                            "Reference Tag #\(referenceTagID)"
                        )
                        .font(
                            .headline
                        )
                        .foregroundStyle(
                            .white
                        )
                    }
                }


                // MARK: AprilTag Map

                AprilTagMapView(
                    mapBuilder: mapBuilder,
                    track: track
                )


                Spacer()


                // MARK: Detected Tags

                Text(
                    "\(mapBuilder.mapPoints.count) AprilTags mapped"
                )
                .font(
                    .caption
                )
                .foregroundStyle(
                    .white.opacity(0.7)
                )


                // MARK: Save

                Button(
                    "Save AprilTag Positions"
                ) {

                    showNameDialog =
                        true
                }
                .buttonStyle(
                    .borderedProminent
                )
                .disabled(
                    mapBuilder.referenceTagID == nil
                )
                
                
            }
            .padding(24)
            
            if isCreatingMap {

                CreateMapView(
                    mapBuilder:
                        mapBuilder,

                    gameMapStore:
                        gameMapStore
                )
            }
            
            
        }
        .alert(
            "Map Name",
            isPresented:
                $showNameDialog
        ) {

            TextField(
                "Name",
                text:
                    $mapName
            )


            Button(
                "Cancel",
                role:
                    .cancel
            ) {}


            Button(
                "Save"
            ) {

                saveMap()
            }
            .disabled(
                mapName
                    .trimmingCharacters(
                        in:
                            .whitespacesAndNewlines
                    )
                    .isEmpty
            )

        } message: {

            Text(
                "Enter a name for the new game map."
            )
        }
    }


    // MARK: - Save Map

    private func saveMap() {

        let name =
            mapName
                .trimmingCharacters(
                    in:
                        .whitespacesAndNewlines
                )


        guard name.isEmpty == false
        else {
            return
        }


        guard let gameMap =
            mapBuilder.createGameMap(
                name:
                    name
            )
        else {
            return
        }


        gameMapStore.save(
            gameMap
        )
    }
}
